declare -a hw_array=(
  # "MM_EXP/MM_EXPv1_0_Z1"
  # "MM_EXP/MM_EXPv1_0_KRIA"
  "DMA_EXP/DMA_EXPv1_0_KRIA"
  "DMA_EXP/DMA_EXPv2_0_KRIA"
  "DMA_EXP/DMA_EXPv3_0_KRIA"
  "DMA_EXP/DMA_EXPv4_0_KRIA"
  # "DMA_EXP/DMA_EXPv2_1_KRIA"
  # "DMA_EXP/DMA_EXPv3_1_KRIA"
  # "DMA_EXP/DMA_EXPv4_1_KRIA"

  # "DMA_EXP/DMA_EXPv1_0_Z1"
  # "DMA_EXP/DMA_EXPv2_0_Z1"
  # "DMA_EXP/DMA_EXPv3_0_Z1"
  # "DMA_EXP/DMA_EXPv4_0_Z1"
  # "DMA_EXP/DMA_EXPv2_1_Z1"
  # "DMA_EXP/DMA_EXPv3_1_Z1"
  # "DMA_EXP/DMA_EXPv4_1_Z1"
)